version: '3.7'
services:
    db:
        image: postgres:12.1
        ports:
            - "5432:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            SSH_AUTH_SOCK: /auth.sock
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: brefnshare

    fpm:
        hostname: fpm
        build: ./services/fpm/
        ports:
            - "9000:9000"
        volumes:
            - ./data/www:/var/www/html:cached

    nginx:
        image: nginx:1.17
        ports:
            - "80:80"
        volumes:
            - ./data/www:/var/www/html:cached
            - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: tp@postgres.com
            PGADMIN_DEFAULT_PASSWORD: tp
        ports:
            - "8081:80"
